src/admin/models/Text.php
<?php
/**
 * This file is part of the Webkar project.
 *
 * (c) Webkar project <http://github.com/omidmm/>
 *
 * For the full copyright and license information, please view the LICENSE,Or visit to webkar.net 
 *
 * file that was distributed with this source code.
  * @link http://www.webkar.net/
 * @copyright Copyright (c) 2018 webkar 
 * @license http://www.webkar.net/license/
 */
namespace omidmm\text\admin\models;

use Yii;
use omidmm\admin\admin\behaviors\CacheFlush;
use omidmm\admin\admin\behaviors\PersianSluggableBehavior;
use omidmm\language\admin\behaviors\TranslateableBehavior;
use yii\behaviors\SluggableBehavior;

class Text extends \omidmm\admin\admin\components\ActiveRecord
{
    const CACHE_KEY = 'progsoft_text';
    public static function tableName()
    {
        return '{{%texts}}';
    }

    public function rules()
    {
        return [
            ['text_id', 'number', 'integerOnly' => true],
            [['text', 'title'] ,'required'],
            [['text', 'title'],'trim'],
            ['title','string','max'=>255],
////            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('progsoft', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            [['slug', 'lang_id'], 'unique', 'targetAttribute' => ['slug','lang_id']],
            ['lang_id','default','value'=>Yii::$app->language]
        ];
    }

    public function attributeLabels()
    {
        return [
           'title' => Yii::t('progsoft', 'Title'),
            'text' => Yii::t('progsoft', 'Text'),
            'slug' => Yii::t('progsoft', 'Slug'),
        ];
    }
           

    public function behaviors()
    {
        return [
            CacheFlush::className(),
             'sluggable' => [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true
            ],
            'translate'=>[
                'class'=>TranslateableBehavior::className(),
                 'attributes'=>['title','text'],
            ],

        ];
    }

}

src/admin/controllers/AController.php
<?php
/**
 * This file is part of the Webkar project.
 *
 * (c) Webkar project <http://github.com/omidmm/>
 *
 * For the full copyright and license information, please view the LICENSE,Or visit to webkar.net 
 *
 * file that was distributed with this source code.
  * @link http://www.webkar.net/
 * @copyright Copyright (c) 2018 webkar 
 * @license http://www.webkar.net/license/
 */
namespace omidmm\text\admin\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;

use omidmm\admin\admin\components\Controller;
use omidmm\text\admin\models\Text;

class AController extends Controller
{
    public $rootActions = ['create', 'delete'];

    public function actionIndex()
    {
        $data = new ActiveDataProvider([
            'query' => Text::find(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionCreate($slug = null)
    {
        $model = new Text;
        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if($model->save()){
                    $this->flash('success', Yii::t('modules/text', 'Text created'));
                    return $this->redirect(['/admin/'.$this->module->id]);
                }
                else{
                    $this->flash('error', Yii::t('progsoft', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        }
        else {
            if($slug){
                $model->slug = $slug;
            }
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }


    public function actionEdit($id)
    {
        $model = Text::findOne($id);
        if($model === null){
            $this->flash('error', Yii::t('progsoft', 'Not found'));
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if($model->save()){
                    $this->flash('success', Yii::t('modules/text', 'Text updated'));
                }
                else{
                    $this->flash('error', Yii::t('progsoft', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        if(($model = Text::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('progsoft', 'Not found');
        }
        return $this->formatResponse(Yii::t('modules/text', 'Text deleted'));
    }
}

src/admin/views/a/_form.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use yii\helpers\ArrayHelper;
    use yii\helpers\Url;
    use omidmm\admin\admin\widgets\Redactor;
?>
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['class' => 'model-form']
]); ?>
<?=  \omidmm\language\admin\widgets\language\LanguageFormSelector::widget(['model' => $model,'attribute' => 'lang_id'])  ?>
<?= $form->field($model,'title')->textInput() ?>
<?=
    $form->field($model, 'text')->widget(\dominus77\tinymce\TinyMce::className(), [
        'options' => [
            'rows' => 10,
            'placeholder' => true,
        ],
        'language' => (Yii::$app->language == 'fa-IR')? 'fa':Yii::$app->language,
        'clientOptions' => [
            'menubar' => true,
            'statusbar' => true,
            'theme' => 'modern',
            'skin' => 'lightgray-gradient', //charcoal, tundora, lightgray-gradient, lightgray
            'plugins' => [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable",
            ],
            'noneditable_noneditable_class' => 'fa',
            'extended_valid_elements' => 'span[class|style]',
            'toolbar1' => "undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            'toolbar2' => "print preview media | forecolor backcolor emoticons | codesample",
            'image_advtab' => true,
            'templates' => [
                [
                    'title' => 'Test template 1',
                    'content' => 'Test 1',
                ],
                [
                    'title' => 'Test template 2',
                    'content' => 'Test 2',
                ]
            ],
            'content_css' => [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css',
            ]
        ],
        'fileManager' => [
            'class' => \dominus77\tinymce\components\MihaildevElFinder::className(),
            'controller' => 'elf1',
            'title' => 'My File Manager',
            'width' => 900,
            'height' => 600,
            'resizable' => 'yes',
        ],
    ]);
?>

<?= (IS_ROOT) ? $form->field($model, 'slug') : '' ?>
<?= Html::submitButton(Yii::t('progsoft', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

src/admin/views/a/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>
<?php if(IS_ROOT) : ?>
    <ul class="nav nav-pills">
        <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
            <a href="<?= $this->context->getReturnUrl(['/admin/'.$module]) ?>">
                <?php if($action === 'edit') : ?>
                    <i class="glyphicon glyphicon-chevron-left font-12"></i>
                <?php endif; ?>
                <?= Yii::t('progsoft', 'List') ?>
            </a>
        </li>
        <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/create']) ?>"><?= Yii::t('progsoft', 'Create') ?></a></li>
    </ul>
    <br/>
<?php elseif($action === 'edit') : ?>
    <ul class="nav nav-pills">
        <li>
            <a href="<?= $this->context->getReturnUrl(['/admin/'.$module])?>">
                <i class="glyphicon glyphicon-chevron-left font-12"></i>
                <?= Yii::t('modules/text', 'Texts') ?>
            </a>
        </li>
    </ul>
    <br/>
<?php endif; ?>

src/admin/views/a/create.php
<?php
$this->title = Yii::t('modules/text', 'Create text');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

src/admin/views/a/edit.php
<?php
$this->title = Yii::t('modules/text', 'Edit text');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

src/admin/views/a/index.php
<?php
use yii\helpers\Url;
$this->title = Yii::t('modules/text', 'Texts');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<?php
// echo \pceuropa\forms\FormBuilder::widget([
//         'test_mode' => false
// ]);

?>

<?php if($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <?php if(IS_ROOT) : ?>
                    <th width="50">#</th>
                <?php endif; ?>
                <th><?= Yii::t('progsoft', 'Title') ?></th>
                 <th><?= Yii::t('progsoft','Lang_id') ?></th>
                <?php if(IS_ROOT) : ?>
                    <th><?= Yii::t('progsoft', 'Slug') ?></th>

                    <th width="30"></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
    <?php foreach($data->models as $item) : ?>
            <tr>
                <?php if(IS_ROOT) : ?>
                <td><?= $item->primaryKey ?></td>
                <?php endif; ?>
                <td><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a></td>
                <td><?= $item->lang_id ?></td>
                <?php if(IS_ROOT) : ?>
                    <td><?= $item->slug ?></td>
                    <td>
						<a href="<?= Url::to(['/admin/'.$module.'/a/delete', 'id' => $item->primaryKey]) ?>" class="btn btn-default confirm-delete" title="<?= Yii::t('progsoft', 'Delete item') ?>"><span class="glyphicon glyphicon-remove"></span></a>
					</td>
                <?php endif; ?>
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('progsoft', 'No records found') ?></p>
<?php endif; ?>

<div>

</div>